Vagrant.configure("2") do |config|
  config.vm.box = "fedora/25-cloud-base"

  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "vagrant-vm-#{i}"
      node.vm.network "public_network", :bridge => 'Realtek RTL8723BE Wireless LAN 802.11n PCI-E NIC', :mac => "AA:BB:CC:DD:EE:0#{i}"
    end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  end
end
