Vagrant.configure("2") do |config|
  config.vm.box = "fedora/25-cloud-base"
  config.vm.hostname = "vagrantvm"
  config.vm.network "public_network", :bridge => 'Realtek RTL8723BE Wireless LAN 802.11n PCI-E NIC', :mac => "AABBCCDDEE01"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
end
