---

- name: kubectl config set-cluster
  shell: |
    kubectl config set-cluster kubernetes-concaf \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://{{ hostvars[groups['master'][0]]['ip'] }}:6443 \
    --kubeconfig=kube-proxy.kubeconfig
  args:
    chdir: /tmp/certs/
    creates: kube-proxy.kubeconfig
  notify:
  - kubectl config set-credentials - kube-proxy
